prompt: 'Верни результат для текста ниже строго в указанном формате JSON, без пояснений, без кавычек вокруг json. 
В summary напиши два-три предложения с основными определениями из текста. 
Посмотри весь список тегов для этого текста и отправь в ответе два-три 
подходящих существующих тега через запятую. Если подходящих нет, то отправь свои 
Пример:
{
  "summary": "…",
  "tags": "тег1, тег2..."
}'